/*
 * Remote API
 * Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CostCalculatorEmploymentParam;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CostCalculatorEstimateParams
 */
public class CostCalculatorEstimateParamsTest {
    private final CostCalculatorEstimateParams model = new CostCalculatorEstimateParams();

    /**
     * Model tests for CostCalculatorEstimateParams
     */
    @Test
    public void testCostCalculatorEstimateParams() {
        // TODO: test CostCalculatorEstimateParams
    }

    /**
     * Test the property 'employerCurrencySlug'
     */
    @Test
    public void employerCurrencySlugTest() {
        // TODO: test employerCurrencySlug
    }

    /**
     * Test the property 'employments'
     */
    @Test
    public void employmentsTest() {
        // TODO: test employments
    }

    /**
     * Test the property 'includeBenefits'
     */
    @Test
    public void includeBenefitsTest() {
        // TODO: test includeBenefits
    }

    /**
     * Test the property 'includeCostBreakdowns'
     */
    @Test
    public void includeCostBreakdownsTest() {
        // TODO: test includeCostBreakdowns
    }

}
