/*
 * Remote API
 * Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CostCalculatorCountryAvailability;
import com.konfigthis.client.model.Currency;
import com.konfigthis.client.model.MinimalRegion;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CostCalculatorCountryLevelRegion
 */
public class CostCalculatorCountryLevelRegionTest {
    private final CostCalculatorCountryLevelRegion model = new CostCalculatorCountryLevelRegion();

    /**
     * Model tests for CostCalculatorCountryLevelRegion
     */
    @Test
    public void testCostCalculatorCountryLevelRegion() {
        // TODO: test CostCalculatorCountryLevelRegion
    }

    /**
     * Test the property 'availability'
     */
    @Test
    public void availabilityTest() {
        // TODO: test availability
    }

    /**
     * Test the property 'childRegions'
     */
    @Test
    public void childRegionsTest() {
        // TODO: test childRegions
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'hasAdditionalFields'
     */
    @Test
    public void hasAdditionalFieldsTest() {
        // TODO: test hasAdditionalFields
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'originalCountrySlug'
     */
    @Test
    public void originalCountrySlugTest() {
        // TODO: test originalCountrySlug
    }

    /**
     * Test the property 'regionSlug'
     */
    @Test
    public void regionSlugTest() {
        // TODO: test regionSlug
    }

}
