/*
 * Remote API
 * Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Country;
import com.konfigthis.client.model.PricingPlanDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FullParamsDeprecated
 */
public class FullParamsDeprecatedTest {
    private final FullParamsDeprecated model = new FullParamsDeprecated();

    /**
     * Model tests for FullParamsDeprecated
     */
    @Test
    public void testFullParamsDeprecated() {
        // TODO: test FullParamsDeprecated
    }

    /**
     * Test the property 'addressDetails'
     */
    @Test
    public void addressDetailsTest() {
        // TODO: test addressDetails
    }

    /**
     * Test the property 'administrativeDetails'
     */
    @Test
    public void administrativeDetailsTest() {
        // TODO: test administrativeDetails
    }

    /**
     * Test the property 'bankAccountDetails'
     */
    @Test
    public void bankAccountDetailsTest() {
        // TODO: test bankAccountDetails
    }

    /**
     * Test the property 'billingAddressDetails'
     */
    @Test
    public void billingAddressDetailsTest() {
        // TODO: test billingAddressDetails
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'contractDetails'
     */
    @Test
    public void contractDetailsTest() {
        // TODO: test contractDetails
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'emergencyContactDetails'
     */
    @Test
    public void emergencyContactDetailsTest() {
        // TODO: test emergencyContactDetails
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'managerId'
     */
    @Test
    public void managerIdTest() {
        // TODO: test managerId
    }

    /**
     * Test the property 'personalDetails'
     */
    @Test
    public void personalDetailsTest() {
        // TODO: test personalDetails
    }

    /**
     * Test the property 'personalEmail'
     */
    @Test
    public void personalEmailTest() {
        // TODO: test personalEmail
    }

    /**
     * Test the property 'pricingPlanDetails'
     */
    @Test
    public void pricingPlanDetailsTest() {
        // TODO: test pricingPlanDetails
    }

    /**
     * Test the property 'provisionalStartDate'
     */
    @Test
    public void provisionalStartDateTest() {
        // TODO: test provisionalStartDate
    }

    /**
     * Test the property 'seniorityDate'
     */
    @Test
    public void seniorityDateTest() {
        // TODO: test seniorityDate
    }

}
