/*
 * Remote API
 * Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CountrySubdivision;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * A supported country on Remote
 */
@ApiModel(description = "A supported country on Remote")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Country {
  public static final String SERIALIZED_NAME_ALPHA2_CODE = "alpha_2_code";
  @SerializedName(SERIALIZED_NAME_ALPHA2_CODE)
  private String alpha2Code;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_COUNTRY_SUBDIVISIONS = "country_subdivisions";
  @SerializedName(SERIALIZED_NAME_COUNTRY_SUBDIVISIONS)
  private List<CountrySubdivision> countrySubdivisions = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SUPPORTED_JSON_SCHEMAS = "supported_json_schemas";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_JSON_SCHEMAS)
  private List<String> supportedJsonSchemas = null;

  public Country() {
  }

  public Country alpha2Code(String alpha2Code) {
    
    
    
    
    this.alpha2Code = alpha2Code;
    return this;
  }

   /**
   * Get alpha2Code
   * @return alpha2Code
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "PT", required = true, value = "")

  public String getAlpha2Code() {
    return alpha2Code;
  }


  public void setAlpha2Code(String alpha2Code) {
    
    
    
    this.alpha2Code = alpha2Code;
  }


  public Country code(String code) {
    
    
    
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "PRT", required = true, value = "")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    
    
    
    this.code = code;
  }


  public Country countrySubdivisions(List<CountrySubdivision> countrySubdivisions) {
    
    
    
    
    this.countrySubdivisions = countrySubdivisions;
    return this;
  }

  public Country addCountrySubdivisionsItem(CountrySubdivision countrySubdivisionsItem) {
    if (this.countrySubdivisions == null) {
      this.countrySubdivisions = new ArrayList<>();
    }
    this.countrySubdivisions.add(countrySubdivisionsItem);
    return this;
  }

   /**
   * Get countrySubdivisions
   * @return countrySubdivisions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CountrySubdivision> getCountrySubdivisions() {
    return countrySubdivisions;
  }


  public void setCountrySubdivisions(List<CountrySubdivision> countrySubdivisions) {
    
    
    
    this.countrySubdivisions = countrySubdivisions;
  }


  public Country name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Portugal", required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public Country supportedJsonSchemas(List<String> supportedJsonSchemas) {
    
    
    
    
    this.supportedJsonSchemas = supportedJsonSchemas;
    return this;
  }

  public Country addSupportedJsonSchemasItem(String supportedJsonSchemasItem) {
    if (this.supportedJsonSchemas == null) {
      this.supportedJsonSchemas = new ArrayList<>();
    }
    this.supportedJsonSchemas.add(supportedJsonSchemasItem);
    return this;
  }

   /**
   * Get supportedJsonSchemas
   * @return supportedJsonSchemas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSupportedJsonSchemas() {
    return supportedJsonSchemas;
  }


  public void setSupportedJsonSchemas(List<String> supportedJsonSchemas) {
    
    
    
    this.supportedJsonSchemas = supportedJsonSchemas;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Country instance itself
   */
  public Country putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Country country = (Country) o;
    return Objects.equals(this.alpha2Code, country.alpha2Code) &&
        Objects.equals(this.code, country.code) &&
        Objects.equals(this.countrySubdivisions, country.countrySubdivisions) &&
        Objects.equals(this.name, country.name) &&
        Objects.equals(this.supportedJsonSchemas, country.supportedJsonSchemas)&&
        Objects.equals(this.additionalProperties, country.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(alpha2Code, code, countrySubdivisions, name, supportedJsonSchemas, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Country {\n");
    sb.append("    alpha2Code: ").append(toIndentedString(alpha2Code)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    countrySubdivisions: ").append(toIndentedString(countrySubdivisions)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    supportedJsonSchemas: ").append(toIndentedString(supportedJsonSchemas)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("alpha_2_code");
    openapiFields.add("code");
    openapiFields.add("country_subdivisions");
    openapiFields.add("name");
    openapiFields.add("supported_json_schemas");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("alpha_2_code");
    openapiRequiredFields.add("code");
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Country
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Country.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Country is not found in the empty JSON string", Country.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Country.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("alpha_2_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alpha_2_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alpha_2_code").toString()));
      }
      if (!jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if (jsonObj.get("country_subdivisions") != null && !jsonObj.get("country_subdivisions").isJsonNull()) {
        JsonArray jsonArraycountrySubdivisions = jsonObj.getAsJsonArray("country_subdivisions");
        if (jsonArraycountrySubdivisions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("country_subdivisions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `country_subdivisions` to be an array in the JSON string but got `%s`", jsonObj.get("country_subdivisions").toString()));
          }

          // validate the optional field `country_subdivisions` (array)
          for (int i = 0; i < jsonArraycountrySubdivisions.size(); i++) {
            CountrySubdivision.validateJsonObject(jsonArraycountrySubdivisions.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("supported_json_schemas") != null && !jsonObj.get("supported_json_schemas").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `supported_json_schemas` to be an array in the JSON string but got `%s`", jsonObj.get("supported_json_schemas").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Country.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Country' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Country> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Country.class));

       return (TypeAdapter<T>) new TypeAdapter<Country>() {
           @Override
           public void write(JsonWriter out, Country value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Country read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Country instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Country given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Country
  * @throws IOException if the JSON string is invalid with respect to Country
  */
  public static Country fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Country.class);
  }

 /**
  * Convert an instance of Country to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

