/*
 * Remote API
 * Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CreateWebhookCallbackParams;
import com.konfigthis.client.model.SuccessResponse;
import com.konfigthis.client.model.WebhookCallbackResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhookCallbacksApi
 */
@Disabled
public class WebhookCallbacksApiTest {

    private static WebhookCallbacksApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new WebhookCallbacksApi(apiClient);
    }

    /**
     * Delete a Webhook Callback
     *
     * Delete a callback previously registered for webhooks
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCallbackTest() throws ApiException {
        String id = null;
        SuccessResponse response = api.deleteCallback(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Create a Webhook Callback
     *
     * Register a callback to be used for webhooks
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerCallbackTest() throws ApiException {
        String url = null;
        List<String> subscribedEvents = null;
        WebhookCallbackResponse response = api.registerCallback(url)
                .subscribedEvents(subscribedEvents)
                .execute();
        // TODO: test validations
    }

}
